# Generated by Django 5.0.6 on 2024-06-05 23:35

import notifications.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("sms", "SMS"), ("push", "Push")],
                        max_length=20,
                        validators=[
                            notifications.validations.validate_notification_type
                        ],
                    ),
                ),
                ("message", models.TextField()),
                ("read_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
