# Generated by Django 5.0.6 on 2024-06-05 23:35

import cars.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[cars.validations.validate_year]
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(
                        max_length=20,
                        validators=[cars.validations.validate_license_plate],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
