# Generated by Django 5.0.6 on 2024-06-05 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("live_location", "0001_initial"),
        ("reqs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livelocation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_locations",
                to="reqs.request",
            ),
        ),
    ]
